[package]
name = "waterfall"
version = "0.1.0"
authors = ["Brian Martin <brayniac@gmail.com>"]

license = "MIT"

readme = "README.md"

description = "[placeholder] waterfall data visualization"

documentation = "https://brayniac.github.io/waterfall"
homepage = "https://github.com/brayniac/waterfall"
repository = "https://github.com/brayniac/waterfall"
